# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
        ('secrets', '0002_secret_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_like', to='logreg.User')),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_like', to='secrets.Secret')),
            ],
        ),
    ]
